name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Checkstyle
        run: echo "Checkstyle would run here (requires setup)"

      - name: Compile Java code
        run: javac -d out $(find src -name "*.java")

      - name: Generate Javadoc
        run: |
          mkdir -p docs
          javadoc -d docs $(find src -name "*.java")

      - steps:
          - name: Compile Java code
            run: |
              mkdir -p out
              javac -cp "lib/*" -d out $(find src -name "*.java")
          - name: Run unit tests
            run: |
              java -jar lib/junit-platform-console-standalone-1.10.0.jar \
                --class-path out \
                --scan-class-path
        
