name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.323.0

      - name: Set up JDK
        uses: actions/setup-java@v2.323.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java source files
        run: |
          mkdir -p out
          javac -cp "lib/*" -d out $(find src/main -name "*.java")

      - name: Compile test classes
        run: |
          mkdir -p test-classes
          javac -cp "lib/*:out" -d test-classes $(find src/test -name "*.java")

      - name: Run unit tests
        run: |
          java -jar lib/junit-platform-console-standalone-*.jar \
            --class-path out:test-classes \
            --scan-class-path

      - name: Generate Javadoc
        run: |
          mkdir -p docs
          javadoc -cp "lib/*" -d docs $(find src/main -name "*.java")

      - name: Upload Javadoc
        uses: actions/upload-artifact@v2.323.0
        with:
          name: javadoc
          path: docs
