name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java source files
        run: |
          mkdir -p out
          javac -cp "lib/*" -d out $(find src -name "*.java")

      - name: Compile test classes
        run: |
          mkdir -p test-classes
          javac -cp "lib/*:out" -d test-classes $(find src/test -name "*.java")

      - name: Run unit tests
        run: |
          java -cp "lib/*:out:test-classes" org.junit.platform.console.ConsoleLauncher --scan-classpath


      - name: Generate Javadoc
        run: |
          mkdir -p docs
          javadoc -cp "lib/*" -d docs $(find src/main -name "*.java")
